# Generated by Django 2.1.1 on 2018-09-09 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.DecimalField(decimal_places=0, max_digits=7, primary_key=True, serialize=False)),
                ('department', models.DecimalField(decimal_places=0, max_digits=2)),
                ('name', models.CharField(max_length=50)),
                ('unit_count', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OfferedCourse',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('semester', models.DecimalField(decimal_places=0, max_digits=3)),
                ('group', models.DecimalField(decimal_places=0, max_digits=2)),
                ('instructor', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50, null=True)),
                ('gender_spec', models.NullBooleanField()),
                ('description', models.CharField(max_length=100, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Courses.Course')),
                ('times', models.ManyToManyField(to='Courses.ClassTime')),
            ],
        ),
    ]
