# Generated by Django 2.1.1 on 2018-09-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Courses', '0002_auto_20180904_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classtime',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
